language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
# command to run tests
script:
  - nosetests ./tests/*.py
  - pycodestyle --max-line-length=120 ./tests/*.py
  - pycodestyle --max-line-length=120 --ignore=W605,W504 ./tntfuzzer/*.py
